# Docker Compose file for Workout Tracker
# Secure configuration with internal networking

networks:
  workout-internal:
    driver: bridge

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./postgres-ssl:/var/lib/postgresql/ssl:ro
      - ./postgres-init.sh:/usr/local/bin/postgres-init.sh:ro
    command: /usr/local/bin/postgres-init.sh
    networks:
      - workout-internal
    # Database is NOT exposed to host network for security

  web:
    build: .
    restart: always
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - workout-internal

volumes:
  pgdata:
