version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: workout_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "8080:5000"
    environment:
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://postgres:password@db:5432/workout_tracker
      - FLASK_DEBUG=False
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
