import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default tseslint.config(
	{
		ignores: [
			'dist',
			'.wrangler',
			'node_modules',
			'*.config.*',
			'*.d.ts'
		]
	},
	js.configs.recommended,
	...tseslint.configs.recommendedTypeChecked,
	...tseslint.configs.strictTypeChecked,
	{
		files: ['**/*.{ts,tsx}'],
		plugins: {
			react,
			'react-hooks': reactHooks,
			'jsx-a11y': jsxA11y,
			import: importPlugin
		},
		languageOptions: {
			parser: tseslint.parser,
			parserOptions: {
				ecmaVersion: 'latest',
				sourceType: 'module',
				ecmaFeatures: {
					jsx: true
				},
				project: [join(__dirname, 'tsconfig.json')],
				tsconfigRootDir: __dirname
			},
			globals: {
				browser: true,
				es2022: true,
				node: true
			}
		},
		settings: {
			react: {
				version: 'detect'
			},
			'import/resolver': {
				node: {
					extensions: ['.js', '.jsx', '.ts', '.tsx']
				}
			}
		},
		rules: {
			'@typescript-eslint/array-type': ['error', { 'default': 'array-simple' }],
			'@typescript-eslint/consistent-generic-constructors': ['error', 'constructor'],
			'@typescript-eslint/consistent-indexed-object-style': ['error', 'record'],
			'@typescript-eslint/consistent-type-definitions': 'error',
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/explicit-member-accessibility': 'off',
			'@typescript-eslint/no-array-delete': 'off',
			'@typescript-eslint/no-base-to-string': 'off',
			'@typescript-eslint/no-confusing-void-expression': 'off',
		'@typescript-eslint/no-duplicate-enum-values': 'off',
		'@typescript-eslint/no-dynamic-delete': 'off',
		'@typescript-eslint/no-extraneous-class': 'off',
		'@typescript-eslint/no-for-in-array': 'error',
		'@typescript-eslint/no-inferrable-types': 'off',
		'@typescript-eslint/no-invalid-void-type': 'error',
		'@typescript-eslint/no-misused-new': 'off',
		'@typescript-eslint/no-misused-promises': 'error',
		'@typescript-eslint/no-floating-promises': 'error',
			'@typescript-eslint/no-namespace': 'off',
			'@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
			'@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
			'@typescript-eslint/no-redeclare': 'error',
			'@typescript-eslint/no-redundant-type-constituents': 'error',
			'@typescript-eslint/no-require-imports': 'error',
		'@typescript-eslint/no-shadow': 'error',
		'@typescript-eslint/no-this-alias': 'error',
		'@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
			'@typescript-eslint/no-unnecessary-type-arguments': 'error',
			'@typescript-eslint/no-unnecessary-type-assertion': 'error',
			'@typescript-eslint/no-unused-expressions': ['error', { 'allowShortCircuit': true, 'allowTernary': true }],
			'@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_', 'varsIgnorePattern': '^_' }],
			'@typescript-eslint/no-use-before-define': ['error', { 'functions': true, 'classes': true, 'variables': true, 'enums': true, 'typedefs': true }],
		'@typescript-eslint/no-useless-constructor': 'off',
		'@typescript-eslint/no-useless-empty-export': 'error',
		'@typescript-eslint/non-nullable-type-assertion-style': 'error',
		'@typescript-eslint/only-throw-error': 'error',
		'@typescript-eslint/consistent-type-assertions': 'error',
			'@typescript-eslint/parameter-properties': ['error', { 'prefer': 'parameter-property' }],
			'@typescript-eslint/prefer-as-const': 'error',
			'@typescript-eslint/prefer-enum-initializers': 'error',
		'@typescript-eslint/prefer-for-of': 'error',
		'@typescript-eslint/prefer-function-type': 'error',
		'@typescript-eslint/prefer-includes': 'off',
		'@typescript-eslint/prefer-literal-enum-member': ['error', { 'allowBitwiseExpressions': true }],
		'@typescript-eslint/prefer-nullish-coalescing': 'error',
		'@typescript-eslint/no-base-to-string': 'error',
			'@typescript-eslint/prefer-optional-chain': 'error',
			'@typescript-eslint/prefer-readonly': 'off',
			'@typescript-eslint/prefer-reduce-type-parameter': 'error',
			'@typescript-eslint/prefer-regexp-exec': 'off',
			'@typescript-eslint/prefer-string-starts-ends-with': 'error',
			'@typescript-eslint/promise-function-async': 'off',
			'@typescript-eslint/require-array-sort-compare': 'off',
			'@typescript-eslint/restrict-plus-operands': 'off',
			'@typescript-eslint/restrict-template-expressions': 'off',
			'@typescript-eslint/sort-type-constituents': 'off',
			'@typescript-eslint/strict-boolean-expressions': 'off',
			'@typescript-eslint/switch-exhaustiveness-check': 'error',
			'@typescript-eslint/triple-slash-reference': 'error',
			'@typescript-eslint/typedef': 'off',
			'@typescript-eslint/unified-signatures': 'off',
			'@typescript-eslint/consistent-type-assertions': 'off',
			'@typescript-eslint/no-meaningless-void-operator': 'off',
			'react/display-name': 'error',
			'react/jsx-boolean-value': ['error', 'always'],
			'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
			'react/jsx-closing-tag-location': 'error',
			'react/jsx-curly-brace-presence': 'off',
			'react/jsx-curly-newline': 'off',
			'react/jsx-equals-spacing': 'off',
			'react/jsx-first-prop-new-line': 'off',
			'react/jsx-fragments': ['error', 'syntax'],
			'react/jsx-handler-names': 'off',
			'react/jsx-indent': 'off',
			'react/jsx-indent-props': 'off',
			'react/jsx-key': 'error',
		'react/jsx-max-depth': 'off',
		'react/jsx-no-bind': 'error',
		'react/jsx-no-comment-textnodes': 'off',
		'react/jsx-no-constructed-context-values': 'off',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-leaked-render': 'error',
		'react/jsx-no-literals': 'off',
			'react/jsx-no-target-blank': 'error',
			'react/jsx-no-undef': 'error',
			'react/jsx-no-useless-fragment': 'error',
			'react/jsx-one-expression-per-line': 'off',
			'react/jsx-pascal-case': 'error',
			'react/jsx-props-no-spreading': 'off',
			'react/jsx-sort-props': 'off',
			'react/jsx-tag-spacing': ['error', { 'beforeSelfClosing': 'always', 'afterOpening': 'never', 'closingSlash': 'never' }],
			'react/jsx-uses-react': 'error',
			'react/jsx-wrap-multilines': 'off',
			'react-hooks/exhaustive-deps': 'error',
			'react-hooks/rules-of-hooks': 'error',
			'react/no-access-state-in-setstate': 'error',
			'react/no-adjacent-inline-elements': 'error',
			'react/no-array-index-key': 'off',
			'react/no-children-prop': 'error',
			'react/no-danger': 'error',
			'react/no-danger-with-children': 'error',
			'react/no-deprecated': 'error',
			'react/no-did-mount-set-state': 'error',
			'react/no-did-update-set-state': 'error',
			'react/no-direct-mutation-state': 'error',
			'react/no-find-dom-node': 'error',
			'react/no-is-mounted': 'error',
			'react/no-namespace': 'error',
			'react/no-object-type-as-default-prop': 'error',
			'react/no-redundant-should-component-update': 'error',
			'react/no-render-return-value': 'error',
			'react/no-set-state': 'off',
			'react/no-string-refs': 'error',
			'react/no-this-in-sfc': 'error',
			'react/no-typos': 'error',
			'react/no-unknown-property': 'error',
			'react/no-unsafe': 'error',
			'react/prefer-es6-class': 'error',
			'react/prefer-read-only-props': 'off',
			'react/prefer-stateless-function': 'error',
			'react/prop-types': 'error',
			'react/react-in-jsx-scope': 'off',
			'react/require-default-props': 'off',
			'react/require-optimization': 'off',
			'react/self-closing-comp': 'off',
			'react/sort-comp': ['error', { 'order': ['lifecycle', 'everything-else', 'rendering'] }],
			'react/sort-prop-types': 'error',
			'react/style-prop-object': 'error',
			'jsx-a11y/alt-text': 'error',
			'jsx-a11y/anchor-has-content': 'error',
			'jsx-a11y/anchor-is-valid': 'off',
			'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
			'jsx-a11y/aria-props': 'error',
			'jsx-a11y/aria-proptypes': 'error',
			'jsx-a11y/aria-role': ['error', { 'ignoreNonDOM': true }],
			'jsx-a11y/aria-unsupported-elements': 'error',
			'jsx-a11y/click-events-have-key-events': 'error',
			'jsx-a11y/control-has-associated-label': 'off',
			'jsx-a11y/heading-has-content': 'error',
			'jsx-a11y/html-has-lang': 'error',
			'jsx-a11y/iframe-has-title': 'error',
			'jsx-a11y/img-redundant-alt': 'error',
			'jsx-a11y/interactive-supports-focus': 'error',
			'jsx-a11y/label-has-associated-control': ['error', { 'controlComponents': ['Input', 'Select', 'Textarea'] }],
			'jsx-a11y/lang': 'error',
			'jsx-a11y/media-has-caption': 'error',
			'jsx-a11y/mouse-events-have-key-events': 'error',
			'jsx-a11y/no-autofocus': 'off',
			'jsx-a11y/no-distracting-elements': 'error',
			'jsx-a11y/no-noninteractive-element-interactions': 'error',
			'jsx-a11y/no-noninteractive-tabindex': 'error',
			'jsx-a11y/no-redundant-roles': 'error',
			'jsx-a11y/no-static-element-interactions': 'error',
			'jsx-a11y/role-has-required-aria-props': 'error',
			'jsx-a11y/tabindex-no-positive': 'error',
			'import/default': 'error',
		'import/export': 'error',
		'import/named': 'error',
		'import/namespace': 'error',
		'import/no-unresolved': 'off',
		'import/no-duplicates': 'error',
		'import/first': 'off',
			'import/exports-last': 'off',
			'import/no-amd': 'error',
			'import/no-anonymous-default-export': ['error', { 'allowAnonymousClass': false, 'allowAnonymousFunction': false, 'allowArray': false, 'allowArrowFunction': false, 'allowLiteral': false, 'allowObject': true }],
			'import/no-commonjs': 'off',
			'import/no-cycle': 'error',
			'import/no-default-export': 'off',
			'import/no-deprecated': 'error',
			'import/no-dynamic-require': 'error',
			'import/no-empty-named-blocks': 'error',
			'import/no-extraneous-dependencies': 'error',
			'import/no-import-module-exports': 'error',
			'import/no-mutable-exports': 'error',
			'import/no-named-as-default': 'error',
			'import/no-named-as-default-member': 'error',
			'import/no-namespace': 'error',
			'import/no-nodejs-modules': 'off',
			'import/no-relative-packages': 'off',
			'import/no-relative-parent-imports': 'off',
			'import/no-restricted-paths': 'error',
		'import/no-self-import': 'error',
		'import/no-unassigned-import': 'error',
		'import/no-useless-path-segments': 'off',
		'import/no-webpack-loader-syntax': 'error',
		'import/order': ['error', { 'groups': [['builtin', 'external'], 'internal', ['parent', 'sibling'], 'index', 'type'] }],
		'import/extensions': 'off',
			'import/newline-after-import': 'off',
			'import/prefer-default-export': 'off',
			'eqeqeq': ['error', 'always'],
			'no-alert': 'error',
			'no-console': 'off',
			'no-constant-binary-expression': 'error',
			'no-constructor-return': 'error',
			'no-debugger': 'error',
			'no-delete-var': 'error',
			'no-duplicate-imports': 'error',
			'no-empty': ['error', { 'allowEmptyCatch': true }],
			'no-empty-character-class': 'error',
			'no-empty-pattern': 'error',
			'no-eval': 'error',
			'no-ex-assign': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-extra-label': 'error',
			'no-fallthrough': ['error', { 'allowEmptyCase': true }],
			'no-floating-decimal': 'error',
			'no-global-assign': 'error',
			'no-implicit-globals': 'error',
			'no-import-assign': 'error',
			'no-inline-comments': 'off',
			'no-inner-declarations': ['error', 'both'],
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-iterator': 'error',
			'no-label-var': 'error',
			'no-labels': ['error', { 'allowLoop': true, 'allowSwitch': true }],
			'no-lone-blocks': 'error',
			'no-loop-func': 'error',
			'no-misleading-character-class': 'error',
			'no-multi-assign': 'error',
			'no-multi-str': 'error',
			'no-negated-condition': 'off',
			'no-nested-ternary': 'off',
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-object': 'error',
			'no-new-wrappers': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-obj-calls': 'error',
			'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'error',
		'no-promise-executor-return': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
			'no-regex-spaces': 'error',
			'no-restricted-exports': ['error', { 'restrictedNamedExports': ['default'] }],
			'no-restricted-imports': ['error', { 'paths': [{ 'name': 'react', 'importNames': ['default'] }] }],
			'no-return-assign': ['error', 'always'],
			'no-return-await': 'off',
			'no-script-url': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
		'no-setter-return': 'error',
		'no-shadow': 'error',
		'no-sparse-arrays': 'error',
			'no-template-curly-in-string': 'error',
			'no-ternary': 'off',
			'no-this-before-super': 'error',
			'no-throw-literal': 'error',
			'no-undef': 'off',
			'no-undef-init': 'error',
			'no-undefined': 'off',
			'no-underscore-dangle': 'off',
			'no-unexpected-multiline': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unneeded-ternary': 'off',
			'no-unreachable': 'error',
			'no-unreachable-loop': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unused-expressions': 'off',
			'no-unused-labels': 'error',
			'no-unused-vars': 'off',
			'no-use-before-define': 'off',
			'no-useless-backreference': 'error',
		'no-useless-call': 'error',
		'no-useless-catch': 'error',
		'no-useless-computed-key': 'off',
		'no-useless-concat': 'error',
		'no-useless-constructor': 'off',
		'no-useless-rename': 'off',
		'no-useless-return': 'error',
		'no-var': 'error',
			'no-with': 'error',
			'object-shorthand': 'off',
			'one-var': 'off',
			'prefer-arrow-callback': 'off',
			'prefer-const': 'error',
			'prefer-destructuring': 'off',
			'prefer-exponentiation-operator': 'error',
			'prefer-named-capture-group': 'off',
			'prefer-numeric-literals': 'off',
			'prefer-object-has-own': 'off',
			'prefer-object-spread': 'off',
			'prefer-reflect': 'off',
			'prefer-regex-literals': 'off',
			'prefer-rest-params': 'off',
			'prefer-spread': 'off',
			'prefer-template': 'error',
			'quote-props': 'off',
			'quotes': 'off',
			'radix': 'off',
			'require-atomic-updates': 'error',
			'require-yield': 'error',
			'sort-imports': 'off',
			'sort-keys': 'off',
			'sort-vars': 'off',
			'space-before-blocks': 'off',
			'space-in-parens': 'off',
			'space-infix-ops': 'off',
			'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
			'spaced-comment': 'off',
			'strict': 'off',
			'symbol-description': 'error',
			'use-isnan': 'error',
			'valid-typeof': ['error', { 'requireStringLiterals': true }],
			'wrap-iife': ['error', 'outside'],
			'yoda': 'off'
		}
	}
);
