export const API = {
  TIMEOUTS: {
    DEFAULT_RETRY_DELAY_MS: 1000,
    STATE_EXPIRY_MS: 10 * 60 * 1000,
    SYNC_LOCK_TIMEOUT_MS: 5 * 60 * 1000,
  },
  LIMITS: {
    MAX_SYNC_RECORDS: 500,
    SAFE_MAX_SQL_VARS: 500,
    TOKEN_REFRESH_THRESHOLD_MINUTES: 5,
  },
} as const;

export const UI = {
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 25,
  },
  TIMING: {
    AUTOSAVE_DELAY_MS: 1000,
    SAVED_INDICATOR_DURATION_MS: 2000,
    QUERY_STALE_TIME_MS: 30 * 1000,
  },
} as const;

export const AUTH = {
  TOKEN_EXPIRY_SECONDS: 4 * 24 * 60 * 60,
  REFRESH_THRESHOLD_SECONDS: 24 * 60 * 60,
  SESSION_COOKIE_MAX_AGE: 4 * 24 * 60 * 60,
} as const;

export const VALIDATION = {
  MAX_NAME_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_NOTES_LENGTH: 2000,
  MAX_MUSCLE_GROUP_LENGTH: 50,
  MAX_SEARCH_TERM_LENGTH: 100,
} as const;
