/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as R1rmTestRouteImport } from './routes/1rm-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts._index'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as TemplatesNewRouteImport } from './routes/templates.new'
import { Route as TemplatesIndexRouteImport } from './routes/templates._index'
import { Route as TemplatesIdRouteImport } from './routes/templates.$id'
import { Route as ProgramsIndexRouteImport } from './routes/programs._index'
import { Route as ExercisesNewRouteImport } from './routes/exercises.new'
import { Route as ExercisesIndexRouteImport } from './routes/exercises._index'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiWorkoutsRouteImport } from './routes/api/workouts'
import { Route as ApiWorkoutSetsRouteImport } from './routes/api/workout-sets'
import { Route as ApiWorkoutExercisesRouteImport } from './routes/api/workout-exercises'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiStreaksRouteImport } from './routes/api/streaks'
import { Route as ApiProgramsRouteImport } from './routes/api/programs'
import { Route as ApiProgramCyclesRouteImport } from './routes/api/program-cycles'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiExercisesRouteImport } from './routes/api/exercises'
import { Route as ApiBadgesRouteImport } from './routes/api/badges'
import { Route as WorkoutsStartTemplateIdRouteImport } from './routes/workouts.start.$templateId'
import { Route as WorkoutsIdSummaryRouteImport } from './routes/workouts.$id_.summary'
import { Route as WorkoutsIdEditRouteImport } from './routes/workouts.$id_.edit'
import { Route as TemplatesIdEditRouteImport } from './routes/templates.$id.edit'
import { Route as ProgramsCycleCycleIdRouteImport } from './routes/programs.cycle.$cycleId_'
import { Route as ProgramsSlugStartRouteImport } from './routes/programs.$slug.start'
import { Route as ExercisesIdEditRouteImport } from './routes/exercises.$id.edit'
import { Route as ApiWorkoutsStatsRouteImport } from './routes/api/workouts.stats'
import { Route as ApiWorkoutsSetsRouteImport } from './routes/api/workouts.sets'
import { Route as ApiWorkoutsPrCountRouteImport } from './routes/api/workouts.pr-count'
import { Route as ApiWorkoutsIdRouteImport } from './routes/api/workouts.$id'
import { Route as ApiUserPreferencesRouteImport } from './routes/api/user.preferences'
import { Route as ApiUser1rmRouteImport } from './routes/api/user.1rm'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates.$id'
import { Route as ApiProgressVolumeRouteImport } from './routes/api/progress.volume'
import { Route as ApiProgressStrengthRouteImport } from './routes/api/progress.strength'
import { Route as ApiProgressPrsRouteImport } from './routes/api/progress.prs'
import { Route as ApiProgramCyclesIdRouteImport } from './routes/api/program-cycles.$id'
import { Route as ApiExercisesCopyFromLibraryRouteImport } from './routes/api/exercises.copy-from-library'
import { Route as ApiExercisesIdRouteImport } from './routes/api/exercises.$id'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAnalyticsTrackRouteImport } from './routes/api/analytics/track'
import { Route as ProgramsCycleCycleIdCompleteRouteImport } from './routes/programs.cycle.$cycleId.complete'
import { Route as ProgramsCycleCycleId1rmUpdateRouteImport } from './routes/programs.cycle.$cycleId.1rm-update'
import { Route as ProgramsCycleCycleId1rmTestRouteImport } from './routes/programs.cycle.$cycleId.1rm-test'
import { Route as ApiWorkoutsSetsSetIdRouteImport } from './routes/api/workouts.sets.$setId'
import { Route as ApiWorkoutsIdExercisesRouteImport } from './routes/api/workouts.$id.exercises'
import { Route as ApiWorkoutsIdCompleteRouteImport } from './routes/api/workouts.$id.complete'
import { Route as ApiTemplatesIdExercisesRouteImport } from './routes/api/templates.$id.exercises'
import { Route as ApiTemplatesIdCopyRouteImport } from './routes/api/templates.$id.copy'
import { Route as ApiProgramCyclesIdWorkoutsRouteImport } from './routes/api/program-cycles.$id.workouts'
import { Route as ApiProgramCyclesIdStartWorkoutRouteImport } from './routes/api/program-cycles.$id.start-workout'
import { Route as ApiProgramCyclesIdCurrentWorkoutRouteImport } from './routes/api/program-cycles.$id.current-workout'
import { Route as ApiProgramCyclesIdCreate1rmTestWorkoutRouteImport } from './routes/api/program-cycles.$id.create-1rm-test-workout'
import { Route as ApiProgramCyclesCycleId1rmTestWorkoutRouteImport } from './routes/api/program-cycles.$cycleId.1rm-test-workout'
import { Route as ApiExercisesIdLastWorkoutSetsRouteImport } from './routes/api/exercises.$id.last-workout-sets'
import { Route as ApiExercisesIdLastWorkoutRouteImport } from './routes/api/exercises.$id.last-workout'
import { Route as ApiWorkoutsIdExercisesReorderRouteImport } from './routes/api/workouts.$id.exercises.reorder'
import { Route as ApiTemplatesIdExercisesReorderRouteImport } from './routes/api/templates.$id.exercises.reorder'
import { Route as ApiTemplatesIdExercisesExerciseIdRouteImport } from './routes/api/templates.$id.exercises.$exerciseId'
import { Route as ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRouteImport } from './routes/api/program-cycles.$id.workouts.$workoutId.reschedule'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const R1rmTestRoute = R1rmTestRouteImport.update({
  id: '/1rm-test',
  path: '/1rm-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/_index',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/workouts/$id',
  path: '/workouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/_index',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/_index',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/exercises/new',
  path: '/exercises/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/_index',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/exercises/$id',
  path: '/exercises/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutsRoute = ApiWorkoutsRouteImport.update({
  id: '/api/workouts',
  path: '/api/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutSetsRoute = ApiWorkoutSetsRouteImport.update({
  id: '/api/workout-sets',
  path: '/api/workout-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutExercisesRoute = ApiWorkoutExercisesRouteImport.update({
  id: '/api/workout-exercises',
  path: '/api/workout-exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreaksRoute = ApiStreaksRouteImport.update({
  id: '/api/streaks',
  path: '/api/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgramsRoute = ApiProgramsRouteImport.update({
  id: '/api/programs',
  path: '/api/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgramCyclesRoute = ApiProgramCyclesRouteImport.update({
  id: '/api/program-cycles',
  path: '/api/program-cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExercisesRoute = ApiExercisesRouteImport.update({
  id: '/api/exercises',
  path: '/api/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgesRoute = ApiBadgesRouteImport.update({
  id: '/api/badges',
  path: '/api/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsStartTemplateIdRoute = WorkoutsStartTemplateIdRouteImport.update({
  id: '/workouts/start/$templateId',
  path: '/workouts/start/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdSummaryRoute = WorkoutsIdSummaryRouteImport.update({
  id: '/workouts/$id_/summary',
  path: '/workouts/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdEditRoute = WorkoutsIdEditRouteImport.update({
  id: '/workouts/$id_/edit',
  path: '/workouts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdEditRoute = TemplatesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TemplatesIdRoute,
} as any)
const ProgramsCycleCycleIdRoute = ProgramsCycleCycleIdRouteImport.update({
  id: '/programs/cycle/$cycleId_',
  path: '/programs/cycle/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugStartRoute = ProgramsSlugStartRouteImport.update({
  id: '/programs/$slug/start',
  path: '/programs/$slug/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdEditRoute = ExercisesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ExercisesIdRoute,
} as any)
const ApiWorkoutsStatsRoute = ApiWorkoutsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiWorkoutsRoute,
} as any)
const ApiWorkoutsSetsRoute = ApiWorkoutsSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => ApiWorkoutsRoute,
} as any)
const ApiWorkoutsPrCountRoute = ApiWorkoutsPrCountRouteImport.update({
  id: '/pr-count',
  path: '/pr-count',
  getParentRoute: () => ApiWorkoutsRoute,
} as any)
const ApiWorkoutsIdRoute = ApiWorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkoutsRoute,
} as any)
const ApiUserPreferencesRoute = ApiUserPreferencesRouteImport.update({
  id: '/api/user/preferences',
  path: '/api/user/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUser1rmRoute = ApiUser1rmRouteImport.update({
  id: '/api/user/1rm',
  path: '/api/user/1rm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTemplatesRoute,
} as any)
const ApiProgressVolumeRoute = ApiProgressVolumeRouteImport.update({
  id: '/api/progress/volume',
  path: '/api/progress/volume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressStrengthRoute = ApiProgressStrengthRouteImport.update({
  id: '/api/progress/strength',
  path: '/api/progress/strength',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressPrsRoute = ApiProgressPrsRouteImport.update({
  id: '/api/progress/prs',
  path: '/api/progress/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgramCyclesIdRoute = ApiProgramCyclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProgramCyclesRoute,
} as any)
const ApiExercisesCopyFromLibraryRoute =
  ApiExercisesCopyFromLibraryRouteImport.update({
    id: '/copy-from-library',
    path: '/copy-from-library',
    getParentRoute: () => ApiExercisesRoute,
  } as any)
const ApiExercisesIdRoute = ApiExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExercisesRoute,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsTrackRoute = ApiAnalyticsTrackRouteImport.update({
  id: '/api/analytics/track',
  path: '/api/analytics/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCycleCycleIdCompleteRoute =
  ProgramsCycleCycleIdCompleteRouteImport.update({
    id: '/programs/cycle/$cycleId/complete',
    path: '/programs/cycle/$cycleId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsCycleCycleId1rmUpdateRoute =
  ProgramsCycleCycleId1rmUpdateRouteImport.update({
    id: '/programs/cycle/$cycleId/1rm-update',
    path: '/programs/cycle/$cycleId/1rm-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsCycleCycleId1rmTestRoute =
  ProgramsCycleCycleId1rmTestRouteImport.update({
    id: '/programs/cycle/$cycleId/1rm-test',
    path: '/programs/cycle/$cycleId/1rm-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkoutsSetsSetIdRoute = ApiWorkoutsSetsSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => ApiWorkoutsSetsRoute,
} as any)
const ApiWorkoutsIdExercisesRoute = ApiWorkoutsIdExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => ApiWorkoutsIdRoute,
} as any)
const ApiWorkoutsIdCompleteRoute = ApiWorkoutsIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiWorkoutsIdRoute,
} as any)
const ApiTemplatesIdExercisesRoute = ApiTemplatesIdExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => ApiTemplatesIdRoute,
} as any)
const ApiTemplatesIdCopyRoute = ApiTemplatesIdCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => ApiTemplatesIdRoute,
} as any)
const ApiProgramCyclesIdWorkoutsRoute =
  ApiProgramCyclesIdWorkoutsRouteImport.update({
    id: '/workouts',
    path: '/workouts',
    getParentRoute: () => ApiProgramCyclesIdRoute,
  } as any)
const ApiProgramCyclesIdStartWorkoutRoute =
  ApiProgramCyclesIdStartWorkoutRouteImport.update({
    id: '/start-workout',
    path: '/start-workout',
    getParentRoute: () => ApiProgramCyclesIdRoute,
  } as any)
const ApiProgramCyclesIdCurrentWorkoutRoute =
  ApiProgramCyclesIdCurrentWorkoutRouteImport.update({
    id: '/current-workout',
    path: '/current-workout',
    getParentRoute: () => ApiProgramCyclesIdRoute,
  } as any)
const ApiProgramCyclesIdCreate1rmTestWorkoutRoute =
  ApiProgramCyclesIdCreate1rmTestWorkoutRouteImport.update({
    id: '/create-1rm-test-workout',
    path: '/create-1rm-test-workout',
    getParentRoute: () => ApiProgramCyclesIdRoute,
  } as any)
const ApiProgramCyclesCycleId1rmTestWorkoutRoute =
  ApiProgramCyclesCycleId1rmTestWorkoutRouteImport.update({
    id: '/$cycleId/1rm-test-workout',
    path: '/$cycleId/1rm-test-workout',
    getParentRoute: () => ApiProgramCyclesRoute,
  } as any)
const ApiExercisesIdLastWorkoutSetsRoute =
  ApiExercisesIdLastWorkoutSetsRouteImport.update({
    id: '/last-workout-sets',
    path: '/last-workout-sets',
    getParentRoute: () => ApiExercisesIdRoute,
  } as any)
const ApiExercisesIdLastWorkoutRoute =
  ApiExercisesIdLastWorkoutRouteImport.update({
    id: '/last-workout',
    path: '/last-workout',
    getParentRoute: () => ApiExercisesIdRoute,
  } as any)
const ApiWorkoutsIdExercisesReorderRoute =
  ApiWorkoutsIdExercisesReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiWorkoutsIdExercisesRoute,
  } as any)
const ApiTemplatesIdExercisesReorderRoute =
  ApiTemplatesIdExercisesReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiTemplatesIdExercisesRoute,
  } as any)
const ApiTemplatesIdExercisesExerciseIdRoute =
  ApiTemplatesIdExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => ApiTemplatesIdExercisesRoute,
  } as any)
const ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute =
  ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRouteImport.update({
    id: '/$workoutId/reschedule',
    path: '/$workoutId/reschedule',
    getParentRoute: () => ApiProgramCyclesIdWorkoutsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1rm-test': typeof R1rmTestRoute
  '/achievements': typeof AchievementsRoute
  '/progress': typeof ProgressRoute
  '/api/badges': typeof ApiBadgesRoute
  '/api/exercises': typeof ApiExercisesRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/program-cycles': typeof ApiProgramCyclesRouteWithChildren
  '/api/programs': typeof ApiProgramsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/workout-exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout-sets': typeof ApiWorkoutSetsRoute
  '/api/workouts': typeof ApiWorkoutsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/exercises/$id': typeof ExercisesIdRouteWithChildren
  '/exercises': typeof ExercisesIndexRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/programs': typeof ProgramsIndexRoute
  '/templates/$id': typeof TemplatesIdRouteWithChildren
  '/templates': typeof TemplatesIndexRoute
  '/templates/new': typeof TemplatesNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/exercises/$id': typeof ApiExercisesIdRouteWithChildren
  '/api/exercises/copy-from-library': typeof ApiExercisesCopyFromLibraryRoute
  '/api/program-cycles/$id': typeof ApiProgramCyclesIdRouteWithChildren
  '/api/progress/prs': typeof ApiProgressPrsRoute
  '/api/progress/strength': typeof ApiProgressStrengthRoute
  '/api/progress/volume': typeof ApiProgressVolumeRoute
  '/api/templates/$id': typeof ApiTemplatesIdRouteWithChildren
  '/api/user/1rm': typeof ApiUser1rmRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/workouts/$id': typeof ApiWorkoutsIdRouteWithChildren
  '/api/workouts/pr-count': typeof ApiWorkoutsPrCountRoute
  '/api/workouts/sets': typeof ApiWorkoutsSetsRouteWithChildren
  '/api/workouts/stats': typeof ApiWorkoutsStatsRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/programs/$slug/start': typeof ProgramsSlugStartRoute
  '/programs/cycle/$cycleId': typeof ProgramsCycleCycleIdRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/summary': typeof WorkoutsIdSummaryRoute
  '/workouts/start/$templateId': typeof WorkoutsStartTemplateIdRoute
  '/api/exercises/$id/last-workout': typeof ApiExercisesIdLastWorkoutRoute
  '/api/exercises/$id/last-workout-sets': typeof ApiExercisesIdLastWorkoutSetsRoute
  '/api/program-cycles/$cycleId/1rm-test-workout': typeof ApiProgramCyclesCycleId1rmTestWorkoutRoute
  '/api/program-cycles/$id/create-1rm-test-workout': typeof ApiProgramCyclesIdCreate1rmTestWorkoutRoute
  '/api/program-cycles/$id/current-workout': typeof ApiProgramCyclesIdCurrentWorkoutRoute
  '/api/program-cycles/$id/start-workout': typeof ApiProgramCyclesIdStartWorkoutRoute
  '/api/program-cycles/$id/workouts': typeof ApiProgramCyclesIdWorkoutsRouteWithChildren
  '/api/templates/$id/copy': typeof ApiTemplatesIdCopyRoute
  '/api/templates/$id/exercises': typeof ApiTemplatesIdExercisesRouteWithChildren
  '/api/workouts/$id/complete': typeof ApiWorkoutsIdCompleteRoute
  '/api/workouts/$id/exercises': typeof ApiWorkoutsIdExercisesRouteWithChildren
  '/api/workouts/sets/$setId': typeof ApiWorkoutsSetsSetIdRoute
  '/programs/cycle/$cycleId/1rm-test': typeof ProgramsCycleCycleId1rmTestRoute
  '/programs/cycle/$cycleId/1rm-update': typeof ProgramsCycleCycleId1rmUpdateRoute
  '/programs/cycle/$cycleId/complete': typeof ProgramsCycleCycleIdCompleteRoute
  '/api/templates/$id/exercises/$exerciseId': typeof ApiTemplatesIdExercisesExerciseIdRoute
  '/api/templates/$id/exercises/reorder': typeof ApiTemplatesIdExercisesReorderRoute
  '/api/workouts/$id/exercises/reorder': typeof ApiWorkoutsIdExercisesReorderRoute
  '/api/program-cycles/$id/workouts/$workoutId/reschedule': typeof ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1rm-test': typeof R1rmTestRoute
  '/achievements': typeof AchievementsRoute
  '/progress': typeof ProgressRoute
  '/api/badges': typeof ApiBadgesRoute
  '/api/exercises': typeof ApiExercisesRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/program-cycles': typeof ApiProgramCyclesRouteWithChildren
  '/api/programs': typeof ApiProgramsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/workout-exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout-sets': typeof ApiWorkoutSetsRoute
  '/api/workouts': typeof ApiWorkoutsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/exercises/$id': typeof ExercisesIdRouteWithChildren
  '/exercises': typeof ExercisesIndexRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/programs': typeof ProgramsIndexRoute
  '/templates/$id': typeof TemplatesIdRouteWithChildren
  '/templates': typeof TemplatesIndexRoute
  '/templates/new': typeof TemplatesNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/exercises/$id': typeof ApiExercisesIdRouteWithChildren
  '/api/exercises/copy-from-library': typeof ApiExercisesCopyFromLibraryRoute
  '/api/program-cycles/$id': typeof ApiProgramCyclesIdRouteWithChildren
  '/api/progress/prs': typeof ApiProgressPrsRoute
  '/api/progress/strength': typeof ApiProgressStrengthRoute
  '/api/progress/volume': typeof ApiProgressVolumeRoute
  '/api/templates/$id': typeof ApiTemplatesIdRouteWithChildren
  '/api/user/1rm': typeof ApiUser1rmRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/workouts/$id': typeof ApiWorkoutsIdRouteWithChildren
  '/api/workouts/pr-count': typeof ApiWorkoutsPrCountRoute
  '/api/workouts/sets': typeof ApiWorkoutsSetsRouteWithChildren
  '/api/workouts/stats': typeof ApiWorkoutsStatsRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/programs/$slug/start': typeof ProgramsSlugStartRoute
  '/programs/cycle/$cycleId': typeof ProgramsCycleCycleIdRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/summary': typeof WorkoutsIdSummaryRoute
  '/workouts/start/$templateId': typeof WorkoutsStartTemplateIdRoute
  '/api/exercises/$id/last-workout': typeof ApiExercisesIdLastWorkoutRoute
  '/api/exercises/$id/last-workout-sets': typeof ApiExercisesIdLastWorkoutSetsRoute
  '/api/program-cycles/$cycleId/1rm-test-workout': typeof ApiProgramCyclesCycleId1rmTestWorkoutRoute
  '/api/program-cycles/$id/create-1rm-test-workout': typeof ApiProgramCyclesIdCreate1rmTestWorkoutRoute
  '/api/program-cycles/$id/current-workout': typeof ApiProgramCyclesIdCurrentWorkoutRoute
  '/api/program-cycles/$id/start-workout': typeof ApiProgramCyclesIdStartWorkoutRoute
  '/api/program-cycles/$id/workouts': typeof ApiProgramCyclesIdWorkoutsRouteWithChildren
  '/api/templates/$id/copy': typeof ApiTemplatesIdCopyRoute
  '/api/templates/$id/exercises': typeof ApiTemplatesIdExercisesRouteWithChildren
  '/api/workouts/$id/complete': typeof ApiWorkoutsIdCompleteRoute
  '/api/workouts/$id/exercises': typeof ApiWorkoutsIdExercisesRouteWithChildren
  '/api/workouts/sets/$setId': typeof ApiWorkoutsSetsSetIdRoute
  '/programs/cycle/$cycleId/1rm-test': typeof ProgramsCycleCycleId1rmTestRoute
  '/programs/cycle/$cycleId/1rm-update': typeof ProgramsCycleCycleId1rmUpdateRoute
  '/programs/cycle/$cycleId/complete': typeof ProgramsCycleCycleIdCompleteRoute
  '/api/templates/$id/exercises/$exerciseId': typeof ApiTemplatesIdExercisesExerciseIdRoute
  '/api/templates/$id/exercises/reorder': typeof ApiTemplatesIdExercisesReorderRoute
  '/api/workouts/$id/exercises/reorder': typeof ApiWorkoutsIdExercisesReorderRoute
  '/api/program-cycles/$id/workouts/$workoutId/reschedule': typeof ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1rm-test': typeof R1rmTestRoute
  '/achievements': typeof AchievementsRoute
  '/progress': typeof ProgressRoute
  '/api/badges': typeof ApiBadgesRoute
  '/api/exercises': typeof ApiExercisesRouteWithChildren
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/program-cycles': typeof ApiProgramCyclesRouteWithChildren
  '/api/programs': typeof ApiProgramsRoute
  '/api/streaks': typeof ApiStreaksRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/templates': typeof ApiTemplatesRouteWithChildren
  '/api/workout-exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout-sets': typeof ApiWorkoutSetsRoute
  '/api/workouts': typeof ApiWorkoutsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/exercises/$id': typeof ExercisesIdRouteWithChildren
  '/exercises/_index': typeof ExercisesIndexRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/programs/_index': typeof ProgramsIndexRoute
  '/templates/$id': typeof TemplatesIdRouteWithChildren
  '/templates/_index': typeof TemplatesIndexRoute
  '/templates/new': typeof TemplatesNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts/_index': typeof WorkoutsIndexRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/exercises/$id': typeof ApiExercisesIdRouteWithChildren
  '/api/exercises/copy-from-library': typeof ApiExercisesCopyFromLibraryRoute
  '/api/program-cycles/$id': typeof ApiProgramCyclesIdRouteWithChildren
  '/api/progress/prs': typeof ApiProgressPrsRoute
  '/api/progress/strength': typeof ApiProgressStrengthRoute
  '/api/progress/volume': typeof ApiProgressVolumeRoute
  '/api/templates/$id': typeof ApiTemplatesIdRouteWithChildren
  '/api/user/1rm': typeof ApiUser1rmRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/workouts/$id': typeof ApiWorkoutsIdRouteWithChildren
  '/api/workouts/pr-count': typeof ApiWorkoutsPrCountRoute
  '/api/workouts/sets': typeof ApiWorkoutsSetsRouteWithChildren
  '/api/workouts/stats': typeof ApiWorkoutsStatsRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/programs/$slug/start': typeof ProgramsSlugStartRoute
  '/programs/cycle/$cycleId_': typeof ProgramsCycleCycleIdRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/workouts/$id_/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id_/summary': typeof WorkoutsIdSummaryRoute
  '/workouts/start/$templateId': typeof WorkoutsStartTemplateIdRoute
  '/api/exercises/$id/last-workout': typeof ApiExercisesIdLastWorkoutRoute
  '/api/exercises/$id/last-workout-sets': typeof ApiExercisesIdLastWorkoutSetsRoute
  '/api/program-cycles/$cycleId/1rm-test-workout': typeof ApiProgramCyclesCycleId1rmTestWorkoutRoute
  '/api/program-cycles/$id/create-1rm-test-workout': typeof ApiProgramCyclesIdCreate1rmTestWorkoutRoute
  '/api/program-cycles/$id/current-workout': typeof ApiProgramCyclesIdCurrentWorkoutRoute
  '/api/program-cycles/$id/start-workout': typeof ApiProgramCyclesIdStartWorkoutRoute
  '/api/program-cycles/$id/workouts': typeof ApiProgramCyclesIdWorkoutsRouteWithChildren
  '/api/templates/$id/copy': typeof ApiTemplatesIdCopyRoute
  '/api/templates/$id/exercises': typeof ApiTemplatesIdExercisesRouteWithChildren
  '/api/workouts/$id/complete': typeof ApiWorkoutsIdCompleteRoute
  '/api/workouts/$id/exercises': typeof ApiWorkoutsIdExercisesRouteWithChildren
  '/api/workouts/sets/$setId': typeof ApiWorkoutsSetsSetIdRoute
  '/programs/cycle/$cycleId/1rm-test': typeof ProgramsCycleCycleId1rmTestRoute
  '/programs/cycle/$cycleId/1rm-update': typeof ProgramsCycleCycleId1rmUpdateRoute
  '/programs/cycle/$cycleId/complete': typeof ProgramsCycleCycleIdCompleteRoute
  '/api/templates/$id/exercises/$exerciseId': typeof ApiTemplatesIdExercisesExerciseIdRoute
  '/api/templates/$id/exercises/reorder': typeof ApiTemplatesIdExercisesReorderRoute
  '/api/workouts/$id/exercises/reorder': typeof ApiWorkoutsIdExercisesReorderRoute
  '/api/program-cycles/$id/workouts/$workoutId/reschedule': typeof ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1rm-test'
    | '/achievements'
    | '/progress'
    | '/api/badges'
    | '/api/exercises'
    | '/api/preferences'
    | '/api/program-cycles'
    | '/api/programs'
    | '/api/streaks'
    | '/api/sync'
    | '/api/templates'
    | '/api/workout-exercises'
    | '/api/workout-sets'
    | '/api/workouts'
    | '/auth/callback'
    | '/auth/signin'
    | '/exercises/$id'
    | '/exercises'
    | '/exercises/new'
    | '/programs'
    | '/templates/$id'
    | '/templates'
    | '/templates/new'
    | '/workouts/$id'
    | '/workouts'
    | '/api/analytics/track'
    | '/api/auth/callback'
    | '/api/auth/me'
    | '/api/auth/signout'
    | '/api/exercises/$id'
    | '/api/exercises/copy-from-library'
    | '/api/program-cycles/$id'
    | '/api/progress/prs'
    | '/api/progress/strength'
    | '/api/progress/volume'
    | '/api/templates/$id'
    | '/api/user/1rm'
    | '/api/user/preferences'
    | '/api/workouts/$id'
    | '/api/workouts/pr-count'
    | '/api/workouts/sets'
    | '/api/workouts/stats'
    | '/exercises/$id/edit'
    | '/programs/$slug/start'
    | '/programs/cycle/$cycleId'
    | '/templates/$id/edit'
    | '/workouts/$id/edit'
    | '/workouts/$id/summary'
    | '/workouts/start/$templateId'
    | '/api/exercises/$id/last-workout'
    | '/api/exercises/$id/last-workout-sets'
    | '/api/program-cycles/$cycleId/1rm-test-workout'
    | '/api/program-cycles/$id/create-1rm-test-workout'
    | '/api/program-cycles/$id/current-workout'
    | '/api/program-cycles/$id/start-workout'
    | '/api/program-cycles/$id/workouts'
    | '/api/templates/$id/copy'
    | '/api/templates/$id/exercises'
    | '/api/workouts/$id/complete'
    | '/api/workouts/$id/exercises'
    | '/api/workouts/sets/$setId'
    | '/programs/cycle/$cycleId/1rm-test'
    | '/programs/cycle/$cycleId/1rm-update'
    | '/programs/cycle/$cycleId/complete'
    | '/api/templates/$id/exercises/$exerciseId'
    | '/api/templates/$id/exercises/reorder'
    | '/api/workouts/$id/exercises/reorder'
    | '/api/program-cycles/$id/workouts/$workoutId/reschedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1rm-test'
    | '/achievements'
    | '/progress'
    | '/api/badges'
    | '/api/exercises'
    | '/api/preferences'
    | '/api/program-cycles'
    | '/api/programs'
    | '/api/streaks'
    | '/api/sync'
    | '/api/templates'
    | '/api/workout-exercises'
    | '/api/workout-sets'
    | '/api/workouts'
    | '/auth/callback'
    | '/auth/signin'
    | '/exercises/$id'
    | '/exercises'
    | '/exercises/new'
    | '/programs'
    | '/templates/$id'
    | '/templates'
    | '/templates/new'
    | '/workouts/$id'
    | '/workouts'
    | '/api/analytics/track'
    | '/api/auth/callback'
    | '/api/auth/me'
    | '/api/auth/signout'
    | '/api/exercises/$id'
    | '/api/exercises/copy-from-library'
    | '/api/program-cycles/$id'
    | '/api/progress/prs'
    | '/api/progress/strength'
    | '/api/progress/volume'
    | '/api/templates/$id'
    | '/api/user/1rm'
    | '/api/user/preferences'
    | '/api/workouts/$id'
    | '/api/workouts/pr-count'
    | '/api/workouts/sets'
    | '/api/workouts/stats'
    | '/exercises/$id/edit'
    | '/programs/$slug/start'
    | '/programs/cycle/$cycleId'
    | '/templates/$id/edit'
    | '/workouts/$id/edit'
    | '/workouts/$id/summary'
    | '/workouts/start/$templateId'
    | '/api/exercises/$id/last-workout'
    | '/api/exercises/$id/last-workout-sets'
    | '/api/program-cycles/$cycleId/1rm-test-workout'
    | '/api/program-cycles/$id/create-1rm-test-workout'
    | '/api/program-cycles/$id/current-workout'
    | '/api/program-cycles/$id/start-workout'
    | '/api/program-cycles/$id/workouts'
    | '/api/templates/$id/copy'
    | '/api/templates/$id/exercises'
    | '/api/workouts/$id/complete'
    | '/api/workouts/$id/exercises'
    | '/api/workouts/sets/$setId'
    | '/programs/cycle/$cycleId/1rm-test'
    | '/programs/cycle/$cycleId/1rm-update'
    | '/programs/cycle/$cycleId/complete'
    | '/api/templates/$id/exercises/$exerciseId'
    | '/api/templates/$id/exercises/reorder'
    | '/api/workouts/$id/exercises/reorder'
    | '/api/program-cycles/$id/workouts/$workoutId/reschedule'
  id:
    | '__root__'
    | '/'
    | '/1rm-test'
    | '/achievements'
    | '/progress'
    | '/api/badges'
    | '/api/exercises'
    | '/api/preferences'
    | '/api/program-cycles'
    | '/api/programs'
    | '/api/streaks'
    | '/api/sync'
    | '/api/templates'
    | '/api/workout-exercises'
    | '/api/workout-sets'
    | '/api/workouts'
    | '/auth/callback'
    | '/auth/signin'
    | '/exercises/$id'
    | '/exercises/_index'
    | '/exercises/new'
    | '/programs/_index'
    | '/templates/$id'
    | '/templates/_index'
    | '/templates/new'
    | '/workouts/$id'
    | '/workouts/_index'
    | '/api/analytics/track'
    | '/api/auth/callback'
    | '/api/auth/me'
    | '/api/auth/signout'
    | '/api/exercises/$id'
    | '/api/exercises/copy-from-library'
    | '/api/program-cycles/$id'
    | '/api/progress/prs'
    | '/api/progress/strength'
    | '/api/progress/volume'
    | '/api/templates/$id'
    | '/api/user/1rm'
    | '/api/user/preferences'
    | '/api/workouts/$id'
    | '/api/workouts/pr-count'
    | '/api/workouts/sets'
    | '/api/workouts/stats'
    | '/exercises/$id/edit'
    | '/programs/$slug/start'
    | '/programs/cycle/$cycleId_'
    | '/templates/$id/edit'
    | '/workouts/$id_/edit'
    | '/workouts/$id_/summary'
    | '/workouts/start/$templateId'
    | '/api/exercises/$id/last-workout'
    | '/api/exercises/$id/last-workout-sets'
    | '/api/program-cycles/$cycleId/1rm-test-workout'
    | '/api/program-cycles/$id/create-1rm-test-workout'
    | '/api/program-cycles/$id/current-workout'
    | '/api/program-cycles/$id/start-workout'
    | '/api/program-cycles/$id/workouts'
    | '/api/templates/$id/copy'
    | '/api/templates/$id/exercises'
    | '/api/workouts/$id/complete'
    | '/api/workouts/$id/exercises'
    | '/api/workouts/sets/$setId'
    | '/programs/cycle/$cycleId/1rm-test'
    | '/programs/cycle/$cycleId/1rm-update'
    | '/programs/cycle/$cycleId/complete'
    | '/api/templates/$id/exercises/$exerciseId'
    | '/api/templates/$id/exercises/reorder'
    | '/api/workouts/$id/exercises/reorder'
    | '/api/program-cycles/$id/workouts/$workoutId/reschedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1rmTestRoute: typeof R1rmTestRoute
  AchievementsRoute: typeof AchievementsRoute
  ProgressRoute: typeof ProgressRoute
  ApiBadgesRoute: typeof ApiBadgesRoute
  ApiExercisesRoute: typeof ApiExercisesRouteWithChildren
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  ApiProgramCyclesRoute: typeof ApiProgramCyclesRouteWithChildren
  ApiProgramsRoute: typeof ApiProgramsRoute
  ApiStreaksRoute: typeof ApiStreaksRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiTemplatesRoute: typeof ApiTemplatesRouteWithChildren
  ApiWorkoutExercisesRoute: typeof ApiWorkoutExercisesRoute
  ApiWorkoutSetsRoute: typeof ApiWorkoutSetsRoute
  ApiWorkoutsRoute: typeof ApiWorkoutsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSigninRoute: typeof AuthSigninRoute
  ExercisesIdRoute: typeof ExercisesIdRouteWithChildren
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  ExercisesNewRoute: typeof ExercisesNewRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  TemplatesIdRoute: typeof TemplatesIdRouteWithChildren
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  WorkoutsIdRoute: typeof WorkoutsIdRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  ApiAnalyticsTrackRoute: typeof ApiAnalyticsTrackRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiProgressPrsRoute: typeof ApiProgressPrsRoute
  ApiProgressStrengthRoute: typeof ApiProgressStrengthRoute
  ApiProgressVolumeRoute: typeof ApiProgressVolumeRoute
  ApiUser1rmRoute: typeof ApiUser1rmRoute
  ApiUserPreferencesRoute: typeof ApiUserPreferencesRoute
  ProgramsSlugStartRoute: typeof ProgramsSlugStartRoute
  ProgramsCycleCycleIdRoute: typeof ProgramsCycleCycleIdRoute
  WorkoutsIdEditRoute: typeof WorkoutsIdEditRoute
  WorkoutsIdSummaryRoute: typeof WorkoutsIdSummaryRoute
  WorkoutsStartTemplateIdRoute: typeof WorkoutsStartTemplateIdRoute
  ProgramsCycleCycleId1rmTestRoute: typeof ProgramsCycleCycleId1rmTestRoute
  ProgramsCycleCycleId1rmUpdateRoute: typeof ProgramsCycleCycleId1rmUpdateRoute
  ProgramsCycleCycleIdCompleteRoute: typeof ProgramsCycleCycleIdCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1rm-test': {
      id: '/1rm-test'
      path: '/1rm-test'
      fullPath: '/1rm-test'
      preLoaderRoute: typeof R1rmTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/_index': {
      id: '/workouts/_index'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/workouts/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/_index': {
      id: '/templates/_index'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id': {
      id: '/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/_index': {
      id: '/programs/_index'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/exercises/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/_index': {
      id: '/exercises/_index'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workouts': {
      id: '/api/workouts'
      path: '/api/workouts'
      fullPath: '/api/workouts'
      preLoaderRoute: typeof ApiWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-sets': {
      id: '/api/workout-sets'
      path: '/api/workout-sets'
      fullPath: '/api/workout-sets'
      preLoaderRoute: typeof ApiWorkoutSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-exercises': {
      id: '/api/workout-exercises'
      path: '/api/workout-exercises'
      fullPath: '/api/workout-exercises'
      preLoaderRoute: typeof ApiWorkoutExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streaks': {
      id: '/api/streaks'
      path: '/api/streaks'
      fullPath: '/api/streaks'
      preLoaderRoute: typeof ApiStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/programs': {
      id: '/api/programs'
      path: '/api/programs'
      fullPath: '/api/programs'
      preLoaderRoute: typeof ApiProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/program-cycles': {
      id: '/api/program-cycles'
      path: '/api/program-cycles'
      fullPath: '/api/program-cycles'
      preLoaderRoute: typeof ApiProgramCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exercises': {
      id: '/api/exercises'
      path: '/api/exercises'
      fullPath: '/api/exercises'
      preLoaderRoute: typeof ApiExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badges': {
      id: '/api/badges'
      path: '/api/badges'
      fullPath: '/api/badges'
      preLoaderRoute: typeof ApiBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/start/$templateId': {
      id: '/workouts/start/$templateId'
      path: '/workouts/start/$templateId'
      fullPath: '/workouts/start/$templateId'
      preLoaderRoute: typeof WorkoutsStartTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id_/summary': {
      id: '/workouts/$id_/summary'
      path: '/workouts/$id/summary'
      fullPath: '/workouts/$id/summary'
      preLoaderRoute: typeof WorkoutsIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id_/edit': {
      id: '/workouts/$id_/edit'
      path: '/workouts/$id/edit'
      fullPath: '/workouts/$id/edit'
      preLoaderRoute: typeof WorkoutsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/edit': {
      id: '/templates/$id/edit'
      path: '/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof TemplatesIdEditRouteImport
      parentRoute: typeof TemplatesIdRoute
    }
    '/programs/cycle/$cycleId_': {
      id: '/programs/cycle/$cycleId_'
      path: '/programs/cycle/$cycleId'
      fullPath: '/programs/cycle/$cycleId'
      preLoaderRoute: typeof ProgramsCycleCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug/start': {
      id: '/programs/$slug/start'
      path: '/programs/$slug/start'
      fullPath: '/programs/$slug/start'
      preLoaderRoute: typeof ProgramsSlugStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/edit': {
      id: '/exercises/$id/edit'
      path: '/edit'
      fullPath: '/exercises/$id/edit'
      preLoaderRoute: typeof ExercisesIdEditRouteImport
      parentRoute: typeof ExercisesIdRoute
    }
    '/api/workouts/stats': {
      id: '/api/workouts/stats'
      path: '/stats'
      fullPath: '/api/workouts/stats'
      preLoaderRoute: typeof ApiWorkoutsStatsRouteImport
      parentRoute: typeof ApiWorkoutsRoute
    }
    '/api/workouts/sets': {
      id: '/api/workouts/sets'
      path: '/sets'
      fullPath: '/api/workouts/sets'
      preLoaderRoute: typeof ApiWorkoutsSetsRouteImport
      parentRoute: typeof ApiWorkoutsRoute
    }
    '/api/workouts/pr-count': {
      id: '/api/workouts/pr-count'
      path: '/pr-count'
      fullPath: '/api/workouts/pr-count'
      preLoaderRoute: typeof ApiWorkoutsPrCountRouteImport
      parentRoute: typeof ApiWorkoutsRoute
    }
    '/api/workouts/$id': {
      id: '/api/workouts/$id'
      path: '/$id'
      fullPath: '/api/workouts/$id'
      preLoaderRoute: typeof ApiWorkoutsIdRouteImport
      parentRoute: typeof ApiWorkoutsRoute
    }
    '/api/user/preferences': {
      id: '/api/user/preferences'
      path: '/api/user/preferences'
      fullPath: '/api/user/preferences'
      preLoaderRoute: typeof ApiUserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/1rm': {
      id: '/api/user/1rm'
      path: '/api/user/1rm'
      fullPath: '/api/user/1rm'
      preLoaderRoute: typeof ApiUser1rmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof ApiTemplatesRoute
    }
    '/api/progress/volume': {
      id: '/api/progress/volume'
      path: '/api/progress/volume'
      fullPath: '/api/progress/volume'
      preLoaderRoute: typeof ApiProgressVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/strength': {
      id: '/api/progress/strength'
      path: '/api/progress/strength'
      fullPath: '/api/progress/strength'
      preLoaderRoute: typeof ApiProgressStrengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/prs': {
      id: '/api/progress/prs'
      path: '/api/progress/prs'
      fullPath: '/api/progress/prs'
      preLoaderRoute: typeof ApiProgressPrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/program-cycles/$id': {
      id: '/api/program-cycles/$id'
      path: '/$id'
      fullPath: '/api/program-cycles/$id'
      preLoaderRoute: typeof ApiProgramCyclesIdRouteImport
      parentRoute: typeof ApiProgramCyclesRoute
    }
    '/api/exercises/copy-from-library': {
      id: '/api/exercises/copy-from-library'
      path: '/copy-from-library'
      fullPath: '/api/exercises/copy-from-library'
      preLoaderRoute: typeof ApiExercisesCopyFromLibraryRouteImport
      parentRoute: typeof ApiExercisesRoute
    }
    '/api/exercises/$id': {
      id: '/api/exercises/$id'
      path: '/$id'
      fullPath: '/api/exercises/$id'
      preLoaderRoute: typeof ApiExercisesIdRouteImport
      parentRoute: typeof ApiExercisesRoute
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/track': {
      id: '/api/analytics/track'
      path: '/api/analytics/track'
      fullPath: '/api/analytics/track'
      preLoaderRoute: typeof ApiAnalyticsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/cycle/$cycleId/complete': {
      id: '/programs/cycle/$cycleId/complete'
      path: '/programs/cycle/$cycleId/complete'
      fullPath: '/programs/cycle/$cycleId/complete'
      preLoaderRoute: typeof ProgramsCycleCycleIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/cycle/$cycleId/1rm-update': {
      id: '/programs/cycle/$cycleId/1rm-update'
      path: '/programs/cycle/$cycleId/1rm-update'
      fullPath: '/programs/cycle/$cycleId/1rm-update'
      preLoaderRoute: typeof ProgramsCycleCycleId1rmUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/cycle/$cycleId/1rm-test': {
      id: '/programs/cycle/$cycleId/1rm-test'
      path: '/programs/cycle/$cycleId/1rm-test'
      fullPath: '/programs/cycle/$cycleId/1rm-test'
      preLoaderRoute: typeof ProgramsCycleCycleId1rmTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workouts/sets/$setId': {
      id: '/api/workouts/sets/$setId'
      path: '/$setId'
      fullPath: '/api/workouts/sets/$setId'
      preLoaderRoute: typeof ApiWorkoutsSetsSetIdRouteImport
      parentRoute: typeof ApiWorkoutsSetsRoute
    }
    '/api/workouts/$id/exercises': {
      id: '/api/workouts/$id/exercises'
      path: '/exercises'
      fullPath: '/api/workouts/$id/exercises'
      preLoaderRoute: typeof ApiWorkoutsIdExercisesRouteImport
      parentRoute: typeof ApiWorkoutsIdRoute
    }
    '/api/workouts/$id/complete': {
      id: '/api/workouts/$id/complete'
      path: '/complete'
      fullPath: '/api/workouts/$id/complete'
      preLoaderRoute: typeof ApiWorkoutsIdCompleteRouteImport
      parentRoute: typeof ApiWorkoutsIdRoute
    }
    '/api/templates/$id/exercises': {
      id: '/api/templates/$id/exercises'
      path: '/exercises'
      fullPath: '/api/templates/$id/exercises'
      preLoaderRoute: typeof ApiTemplatesIdExercisesRouteImport
      parentRoute: typeof ApiTemplatesIdRoute
    }
    '/api/templates/$id/copy': {
      id: '/api/templates/$id/copy'
      path: '/copy'
      fullPath: '/api/templates/$id/copy'
      preLoaderRoute: typeof ApiTemplatesIdCopyRouteImport
      parentRoute: typeof ApiTemplatesIdRoute
    }
    '/api/program-cycles/$id/workouts': {
      id: '/api/program-cycles/$id/workouts'
      path: '/workouts'
      fullPath: '/api/program-cycles/$id/workouts'
      preLoaderRoute: typeof ApiProgramCyclesIdWorkoutsRouteImport
      parentRoute: typeof ApiProgramCyclesIdRoute
    }
    '/api/program-cycles/$id/start-workout': {
      id: '/api/program-cycles/$id/start-workout'
      path: '/start-workout'
      fullPath: '/api/program-cycles/$id/start-workout'
      preLoaderRoute: typeof ApiProgramCyclesIdStartWorkoutRouteImport
      parentRoute: typeof ApiProgramCyclesIdRoute
    }
    '/api/program-cycles/$id/current-workout': {
      id: '/api/program-cycles/$id/current-workout'
      path: '/current-workout'
      fullPath: '/api/program-cycles/$id/current-workout'
      preLoaderRoute: typeof ApiProgramCyclesIdCurrentWorkoutRouteImport
      parentRoute: typeof ApiProgramCyclesIdRoute
    }
    '/api/program-cycles/$id/create-1rm-test-workout': {
      id: '/api/program-cycles/$id/create-1rm-test-workout'
      path: '/create-1rm-test-workout'
      fullPath: '/api/program-cycles/$id/create-1rm-test-workout'
      preLoaderRoute: typeof ApiProgramCyclesIdCreate1rmTestWorkoutRouteImport
      parentRoute: typeof ApiProgramCyclesIdRoute
    }
    '/api/program-cycles/$cycleId/1rm-test-workout': {
      id: '/api/program-cycles/$cycleId/1rm-test-workout'
      path: '/$cycleId/1rm-test-workout'
      fullPath: '/api/program-cycles/$cycleId/1rm-test-workout'
      preLoaderRoute: typeof ApiProgramCyclesCycleId1rmTestWorkoutRouteImport
      parentRoute: typeof ApiProgramCyclesRoute
    }
    '/api/exercises/$id/last-workout-sets': {
      id: '/api/exercises/$id/last-workout-sets'
      path: '/last-workout-sets'
      fullPath: '/api/exercises/$id/last-workout-sets'
      preLoaderRoute: typeof ApiExercisesIdLastWorkoutSetsRouteImport
      parentRoute: typeof ApiExercisesIdRoute
    }
    '/api/exercises/$id/last-workout': {
      id: '/api/exercises/$id/last-workout'
      path: '/last-workout'
      fullPath: '/api/exercises/$id/last-workout'
      preLoaderRoute: typeof ApiExercisesIdLastWorkoutRouteImport
      parentRoute: typeof ApiExercisesIdRoute
    }
    '/api/workouts/$id/exercises/reorder': {
      id: '/api/workouts/$id/exercises/reorder'
      path: '/reorder'
      fullPath: '/api/workouts/$id/exercises/reorder'
      preLoaderRoute: typeof ApiWorkoutsIdExercisesReorderRouteImport
      parentRoute: typeof ApiWorkoutsIdExercisesRoute
    }
    '/api/templates/$id/exercises/reorder': {
      id: '/api/templates/$id/exercises/reorder'
      path: '/reorder'
      fullPath: '/api/templates/$id/exercises/reorder'
      preLoaderRoute: typeof ApiTemplatesIdExercisesReorderRouteImport
      parentRoute: typeof ApiTemplatesIdExercisesRoute
    }
    '/api/templates/$id/exercises/$exerciseId': {
      id: '/api/templates/$id/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/api/templates/$id/exercises/$exerciseId'
      preLoaderRoute: typeof ApiTemplatesIdExercisesExerciseIdRouteImport
      parentRoute: typeof ApiTemplatesIdExercisesRoute
    }
    '/api/program-cycles/$id/workouts/$workoutId/reschedule': {
      id: '/api/program-cycles/$id/workouts/$workoutId/reschedule'
      path: '/$workoutId/reschedule'
      fullPath: '/api/program-cycles/$id/workouts/$workoutId/reschedule'
      preLoaderRoute: typeof ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRouteImport
      parentRoute: typeof ApiProgramCyclesIdWorkoutsRoute
    }
  }
}

interface ApiExercisesIdRouteChildren {
  ApiExercisesIdLastWorkoutRoute: typeof ApiExercisesIdLastWorkoutRoute
  ApiExercisesIdLastWorkoutSetsRoute: typeof ApiExercisesIdLastWorkoutSetsRoute
}

const ApiExercisesIdRouteChildren: ApiExercisesIdRouteChildren = {
  ApiExercisesIdLastWorkoutRoute: ApiExercisesIdLastWorkoutRoute,
  ApiExercisesIdLastWorkoutSetsRoute: ApiExercisesIdLastWorkoutSetsRoute,
}

const ApiExercisesIdRouteWithChildren = ApiExercisesIdRoute._addFileChildren(
  ApiExercisesIdRouteChildren,
)

interface ApiExercisesRouteChildren {
  ApiExercisesIdRoute: typeof ApiExercisesIdRouteWithChildren
  ApiExercisesCopyFromLibraryRoute: typeof ApiExercisesCopyFromLibraryRoute
}

const ApiExercisesRouteChildren: ApiExercisesRouteChildren = {
  ApiExercisesIdRoute: ApiExercisesIdRouteWithChildren,
  ApiExercisesCopyFromLibraryRoute: ApiExercisesCopyFromLibraryRoute,
}

const ApiExercisesRouteWithChildren = ApiExercisesRoute._addFileChildren(
  ApiExercisesRouteChildren,
)

interface ApiProgramCyclesIdWorkoutsRouteChildren {
  ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute: typeof ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute
}

const ApiProgramCyclesIdWorkoutsRouteChildren: ApiProgramCyclesIdWorkoutsRouteChildren =
  {
    ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute:
      ApiProgramCyclesIdWorkoutsWorkoutIdRescheduleRoute,
  }

const ApiProgramCyclesIdWorkoutsRouteWithChildren =
  ApiProgramCyclesIdWorkoutsRoute._addFileChildren(
    ApiProgramCyclesIdWorkoutsRouteChildren,
  )

interface ApiProgramCyclesIdRouteChildren {
  ApiProgramCyclesIdCreate1rmTestWorkoutRoute: typeof ApiProgramCyclesIdCreate1rmTestWorkoutRoute
  ApiProgramCyclesIdCurrentWorkoutRoute: typeof ApiProgramCyclesIdCurrentWorkoutRoute
  ApiProgramCyclesIdStartWorkoutRoute: typeof ApiProgramCyclesIdStartWorkoutRoute
  ApiProgramCyclesIdWorkoutsRoute: typeof ApiProgramCyclesIdWorkoutsRouteWithChildren
}

const ApiProgramCyclesIdRouteChildren: ApiProgramCyclesIdRouteChildren = {
  ApiProgramCyclesIdCreate1rmTestWorkoutRoute:
    ApiProgramCyclesIdCreate1rmTestWorkoutRoute,
  ApiProgramCyclesIdCurrentWorkoutRoute: ApiProgramCyclesIdCurrentWorkoutRoute,
  ApiProgramCyclesIdStartWorkoutRoute: ApiProgramCyclesIdStartWorkoutRoute,
  ApiProgramCyclesIdWorkoutsRoute: ApiProgramCyclesIdWorkoutsRouteWithChildren,
}

const ApiProgramCyclesIdRouteWithChildren =
  ApiProgramCyclesIdRoute._addFileChildren(ApiProgramCyclesIdRouteChildren)

interface ApiProgramCyclesRouteChildren {
  ApiProgramCyclesIdRoute: typeof ApiProgramCyclesIdRouteWithChildren
  ApiProgramCyclesCycleId1rmTestWorkoutRoute: typeof ApiProgramCyclesCycleId1rmTestWorkoutRoute
}

const ApiProgramCyclesRouteChildren: ApiProgramCyclesRouteChildren = {
  ApiProgramCyclesIdRoute: ApiProgramCyclesIdRouteWithChildren,
  ApiProgramCyclesCycleId1rmTestWorkoutRoute:
    ApiProgramCyclesCycleId1rmTestWorkoutRoute,
}

const ApiProgramCyclesRouteWithChildren =
  ApiProgramCyclesRoute._addFileChildren(ApiProgramCyclesRouteChildren)

interface ApiTemplatesIdExercisesRouteChildren {
  ApiTemplatesIdExercisesExerciseIdRoute: typeof ApiTemplatesIdExercisesExerciseIdRoute
  ApiTemplatesIdExercisesReorderRoute: typeof ApiTemplatesIdExercisesReorderRoute
}

const ApiTemplatesIdExercisesRouteChildren: ApiTemplatesIdExercisesRouteChildren =
  {
    ApiTemplatesIdExercisesExerciseIdRoute:
      ApiTemplatesIdExercisesExerciseIdRoute,
    ApiTemplatesIdExercisesReorderRoute: ApiTemplatesIdExercisesReorderRoute,
  }

const ApiTemplatesIdExercisesRouteWithChildren =
  ApiTemplatesIdExercisesRoute._addFileChildren(
    ApiTemplatesIdExercisesRouteChildren,
  )

interface ApiTemplatesIdRouteChildren {
  ApiTemplatesIdCopyRoute: typeof ApiTemplatesIdCopyRoute
  ApiTemplatesIdExercisesRoute: typeof ApiTemplatesIdExercisesRouteWithChildren
}

const ApiTemplatesIdRouteChildren: ApiTemplatesIdRouteChildren = {
  ApiTemplatesIdCopyRoute: ApiTemplatesIdCopyRoute,
  ApiTemplatesIdExercisesRoute: ApiTemplatesIdExercisesRouteWithChildren,
}

const ApiTemplatesIdRouteWithChildren = ApiTemplatesIdRoute._addFileChildren(
  ApiTemplatesIdRouteChildren,
)

interface ApiTemplatesRouteChildren {
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRouteWithChildren
}

const ApiTemplatesRouteChildren: ApiTemplatesRouteChildren = {
  ApiTemplatesIdRoute: ApiTemplatesIdRouteWithChildren,
}

const ApiTemplatesRouteWithChildren = ApiTemplatesRoute._addFileChildren(
  ApiTemplatesRouteChildren,
)

interface ApiWorkoutsIdExercisesRouteChildren {
  ApiWorkoutsIdExercisesReorderRoute: typeof ApiWorkoutsIdExercisesReorderRoute
}

const ApiWorkoutsIdExercisesRouteChildren: ApiWorkoutsIdExercisesRouteChildren =
  {
    ApiWorkoutsIdExercisesReorderRoute: ApiWorkoutsIdExercisesReorderRoute,
  }

const ApiWorkoutsIdExercisesRouteWithChildren =
  ApiWorkoutsIdExercisesRoute._addFileChildren(
    ApiWorkoutsIdExercisesRouteChildren,
  )

interface ApiWorkoutsIdRouteChildren {
  ApiWorkoutsIdCompleteRoute: typeof ApiWorkoutsIdCompleteRoute
  ApiWorkoutsIdExercisesRoute: typeof ApiWorkoutsIdExercisesRouteWithChildren
}

const ApiWorkoutsIdRouteChildren: ApiWorkoutsIdRouteChildren = {
  ApiWorkoutsIdCompleteRoute: ApiWorkoutsIdCompleteRoute,
  ApiWorkoutsIdExercisesRoute: ApiWorkoutsIdExercisesRouteWithChildren,
}

const ApiWorkoutsIdRouteWithChildren = ApiWorkoutsIdRoute._addFileChildren(
  ApiWorkoutsIdRouteChildren,
)

interface ApiWorkoutsSetsRouteChildren {
  ApiWorkoutsSetsSetIdRoute: typeof ApiWorkoutsSetsSetIdRoute
}

const ApiWorkoutsSetsRouteChildren: ApiWorkoutsSetsRouteChildren = {
  ApiWorkoutsSetsSetIdRoute: ApiWorkoutsSetsSetIdRoute,
}

const ApiWorkoutsSetsRouteWithChildren = ApiWorkoutsSetsRoute._addFileChildren(
  ApiWorkoutsSetsRouteChildren,
)

interface ApiWorkoutsRouteChildren {
  ApiWorkoutsIdRoute: typeof ApiWorkoutsIdRouteWithChildren
  ApiWorkoutsPrCountRoute: typeof ApiWorkoutsPrCountRoute
  ApiWorkoutsSetsRoute: typeof ApiWorkoutsSetsRouteWithChildren
  ApiWorkoutsStatsRoute: typeof ApiWorkoutsStatsRoute
}

const ApiWorkoutsRouteChildren: ApiWorkoutsRouteChildren = {
  ApiWorkoutsIdRoute: ApiWorkoutsIdRouteWithChildren,
  ApiWorkoutsPrCountRoute: ApiWorkoutsPrCountRoute,
  ApiWorkoutsSetsRoute: ApiWorkoutsSetsRouteWithChildren,
  ApiWorkoutsStatsRoute: ApiWorkoutsStatsRoute,
}

const ApiWorkoutsRouteWithChildren = ApiWorkoutsRoute._addFileChildren(
  ApiWorkoutsRouteChildren,
)

interface ExercisesIdRouteChildren {
  ExercisesIdEditRoute: typeof ExercisesIdEditRoute
}

const ExercisesIdRouteChildren: ExercisesIdRouteChildren = {
  ExercisesIdEditRoute: ExercisesIdEditRoute,
}

const ExercisesIdRouteWithChildren = ExercisesIdRoute._addFileChildren(
  ExercisesIdRouteChildren,
)

interface TemplatesIdRouteChildren {
  TemplatesIdEditRoute: typeof TemplatesIdEditRoute
}

const TemplatesIdRouteChildren: TemplatesIdRouteChildren = {
  TemplatesIdEditRoute: TemplatesIdEditRoute,
}

const TemplatesIdRouteWithChildren = TemplatesIdRoute._addFileChildren(
  TemplatesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1rmTestRoute: R1rmTestRoute,
  AchievementsRoute: AchievementsRoute,
  ProgressRoute: ProgressRoute,
  ApiBadgesRoute: ApiBadgesRoute,
  ApiExercisesRoute: ApiExercisesRouteWithChildren,
  ApiPreferencesRoute: ApiPreferencesRoute,
  ApiProgramCyclesRoute: ApiProgramCyclesRouteWithChildren,
  ApiProgramsRoute: ApiProgramsRoute,
  ApiStreaksRoute: ApiStreaksRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiTemplatesRoute: ApiTemplatesRouteWithChildren,
  ApiWorkoutExercisesRoute: ApiWorkoutExercisesRoute,
  ApiWorkoutSetsRoute: ApiWorkoutSetsRoute,
  ApiWorkoutsRoute: ApiWorkoutsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSigninRoute: AuthSigninRoute,
  ExercisesIdRoute: ExercisesIdRouteWithChildren,
  ExercisesIndexRoute: ExercisesIndexRoute,
  ExercisesNewRoute: ExercisesNewRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  TemplatesIdRoute: TemplatesIdRouteWithChildren,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  WorkoutsIdRoute: WorkoutsIdRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  ApiAnalyticsTrackRoute: ApiAnalyticsTrackRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiProgressPrsRoute: ApiProgressPrsRoute,
  ApiProgressStrengthRoute: ApiProgressStrengthRoute,
  ApiProgressVolumeRoute: ApiProgressVolumeRoute,
  ApiUser1rmRoute: ApiUser1rmRoute,
  ApiUserPreferencesRoute: ApiUserPreferencesRoute,
  ProgramsSlugStartRoute: ProgramsSlugStartRoute,
  ProgramsCycleCycleIdRoute: ProgramsCycleCycleIdRoute,
  WorkoutsIdEditRoute: WorkoutsIdEditRoute,
  WorkoutsIdSummaryRoute: WorkoutsIdSummaryRoute,
  WorkoutsStartTemplateIdRoute: WorkoutsStartTemplateIdRoute,
  ProgramsCycleCycleId1rmTestRoute: ProgramsCycleCycleId1rmTestRoute,
  ProgramsCycleCycleId1rmUpdateRoute: ProgramsCycleCycleId1rmUpdateRoute,
  ProgramsCycleCycleIdCompleteRoute: ProgramsCycleCycleIdCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
