CREATE TABLE `whoop_connections` (
	`workos_id` text PRIMARY KEY,
	`access_token_encrypted` text NOT NULL,
	`refresh_token_encrypted` text NOT NULL,
	`token_expires_at` text NOT NULL,
	`whoop_user_id` text NOT NULL,
	`scopes_granted` text NOT NULL,
	`sync_status` text DEFAULT 'active',
	`sync_in_progress` integer DEFAULT false,
	`sync_started_at` text,
	`last_sync_at` text,
	`created_at` text,
	`updated_at` text,
	CONSTRAINT `fk_whoop_connections_workos_id_users_workos_id_fk` FOREIGN KEY (`workos_id`) REFERENCES `users`(`workos_id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `whoop_cycles` (
	`id` text PRIMARY KEY,
	`workos_id` text NOT NULL,
	`date` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`score` integer,
	`effort` real,
	`total_strain` real,
	`average_heart_rate` integer,
	`max_heart_rate` integer,
	`calories_burned` integer,
	`distance` real,
	`steps` integer,
	`time_awake_ms` integer,
	`zone1_ms` integer,
	`zone2_ms` integer,
	`zone3_ms` integer,
	`zone4_ms` integer,
	`zone5_ms` integer,
	`raw_json` text,
	`whoop_created_at` text,
	`whoop_updated_at` text,
	`created_at` text,
	`updated_at` text,
	CONSTRAINT `fk_whoop_cycles_workos_id_users_workos_id_fk` FOREIGN KEY (`workos_id`) REFERENCES `users`(`workos_id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `whoop_recoveries` (
	`id` text PRIMARY KEY,
	`workos_id` text NOT NULL,
	`cycle_id` text,
	`date` text NOT NULL,
	`score` integer,
	`status` text,
	`resting_heart_rate` integer,
	`hrv` real,
	`spo2` real,
	`skin_temp` real,
	`cardiovascular_load` real,
	`musculoskeletal_load` real,
	`raw_json` text,
	`whoop_created_at` text,
	`whoop_updated_at` text,
	`created_at` text,
	`updated_at` text,
	CONSTRAINT `fk_whoop_recoveries_workos_id_users_workos_id_fk` FOREIGN KEY (`workos_id`) REFERENCES `users`(`workos_id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `whoop_sleeps` (
	`id` text PRIMARY KEY,
	`workos_id` text NOT NULL,
	`sleep_date` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`timezone_offset` text,
	`is_nap` integer DEFAULT false,
	`cycle_id` text,
	`quality_score` real,
	`need_base` real,
	`need_strain` real,
	`need_debt` real,
	`in_bed_duration_ms` integer,
	`awake_duration_ms` integer,
	`asleep_duration_ms` integer,
	`light_sleep_duration_ms` integer,
	`rem_sleep_duration_ms` integer,
	`slow_wave_sleep_duration_ms` integer,
	`disruptions` integer,
	`efficiency` real,
	`respiratory_rate` real,
	`raw_json` text,
	`whoop_created_at` text,
	`whoop_updated_at` text,
	`created_at` text,
	`updated_at` text,
	CONSTRAINT `fk_whoop_sleeps_workos_id_users_workos_id_fk` FOREIGN KEY (`workos_id`) REFERENCES `users`(`workos_id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE `whoop_webhook_events` (
	`id` text PRIMARY KEY,
	`workos_id` text,
	`event_type` text NOT NULL,
	`payload_raw` text,
	`received_at` text,
	`processed_at` text,
	`processing_error` text
);
--> statement-breakpoint
CREATE TABLE `whoop_workouts` (
	`id` text PRIMARY KEY,
	`workos_id` text NOT NULL,
	`name` text,
	`sport_id` integer,
	`sport_name` text,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`duration_ms` integer,
	`strain` real,
	`average_heart_rate` integer,
	`max_heart_rate` integer,
	`calories` integer,
	`distance` real,
	`zone1_ms` integer,
	`zone2_ms` integer,
	`zone3_ms` integer,
	`zone4_ms` integer,
	`zone5_ms` integer,
	`raw_json` text,
	`whoop_created_at` text,
	`whoop_updated_at` text,
	`created_at` text,
	`updated_at` text,
	CONSTRAINT `fk_whoop_workouts_workos_id_users_workos_id_fk` FOREIGN KEY (`workos_id`) REFERENCES `users`(`workos_id`) ON DELETE CASCADE
);
